### ISSUE TITLE
rename master branch -> main branch

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/Python-Web-Scraping-Legacy#1]
Looks like this repo has two branches, one called `master` where the materials are and one called `main`, so this needs to be resolved. See [Guidance for changing the default branch name for GitHub repositories](https://github.com/github/renaming)

![image](https://user-images.githubusercontent.com/118965/148593765-7e9e2254-51a5-4e98-8cac-13037374acaa.png)

**Comment by pssachdeva** [comment]
I just renamed the master branch to main. Closing.
