### ISSUE TITLE
README.md - Requirements update

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/Python-Web-Scraping-Legacy#10]
Two issues:

1. The link is broken in the line:

> See the software requirements _here_ 

2. Consider updating requirements:

Currently it is:

> We will assume a basic knowledge of Python. If you've taken the D-Lab's Python Intensive, that should be sufficient.

Change to something along the lines of:

> To best prepare for this workshop we suggest you: 
>1. Have an **intermediate** knowledge of Python
>2. Have taken the D-Lab's Python-Fundamentals
>3. Understand at a basic level what HTML and CSS are
>4. Understand nested and mixed python data structures
>5. Have a basic idea of Natural Language Processing (NLP)

**Comment by georgeberkeley** [comment]
Fixed
