### ISSUE TITLE
Split API workshop into two parts

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/Python-Web-Scraping-Legacy#4]
The API workshop has a lot to review consider breaking into two parts, for example:

**Day 1:**
1. Signup for nytimes api key
2. pynytimes package installation
3. making api calls

> End with the notion the query is just the start, the hard part starts tomorrow in dealing with nested/mixed data structures, and focusing on what field are of interest to you.

**Day 2:**
1. Unpacking JSON
2. Extracting portions of interest
3. Sentiment Analysis
4. A takehome bonus

**Comment by georgeberkeley** [comment]
I like that feedback so I'm thinking I want to do this?

Day 1:
- Intro
- Web scraping with beautiful soup
- Basics of API: sign up for key, install library, show how to make some simple calls

Day 2:
- Continue APIs
- Making more complex calls
- Handling JSON data
- Data Analysis part
- One of the bonus APIs (twitter, reddit, youtube)

**Comment by seanmperez** [comment]
Yea, that sounds great. Apologies, totally neglected to mention the whole webscraping notebook!
