### ISSUE TITLE
Add a walkthrough for nytimes API key signup

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/Python-Web-Scraping-Legacy#6]
We discuss the idea of adding a short video that walks through the entire process of:
1. Singing up for an account on https://developer.nytimes.com/accounts/create
2. Verifying via email
3. Signing in
4. Going to dropdown > Apps
5. Create new App > +NEW APP
6. Make any name 
7. Store the key for the workshop
8. Add the API key string to the empty api_key = "" string

**Comment by georgeberkeley** [comment]
Fixed, I put that in the API full notes markdown file.
